### ISSUE TITLE
[BUG]: Error while removing from bench

### ISSUE THREAD

**Issue by crazy-explore-r** [kid1194/frappe-list-unassign-from#4]
Hello @kid1194,

I'm getting the below error while removing the app.

```
$ bench remove-app frappe_list_unassign_from
Checking if app installed on active sites...
$ /home/frappe/frappe-bench/env/bin/python -m pip uninstall -y frappe_list_unassign_from
Found existing installation: frappe-list-unassign-from 1.0.7
Uninstalling frappe-list-unassign-from-1.0.7:
  Successfully uninstalled frappe-list-unassign-from-1.0.7
ERROR: [Errno 2] No such file or directory: 'apps/frappe-list-unassign-from'
Traceback (most recent call last):
  File "/usr/lib/python3.10/shutil.py", line 815, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'apps/frappe-list-unassign-from' -> 'archived/apps/frappe-list-unassign-from-2023-08-01'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/bench/cli.py", line 127, in cli
    bench_command()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bench/commands/make.py", line 197, in remove_app
    bench.uninstall(app_name, no_backup=no_backup, force=force)
  File "/usr/local/lib/python3.10/dist-packages/bench/bench.py", line 130, in uninstall
    self.apps.remove(App(app, bench=self, to_clone=False), no_backup=no_backup)
  File "/usr/local/lib/python3.10/dist-packages/bench/bench.py", line 317, in remove
    app.remove(no_backup=no_backup)
  File "/usr/local/lib/python3.10/dist-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bench/app.py", line 216, in remove
    shutil.move(active_app_path, archived_app_path)
  File "/usr/lib/python3.10/shutil.py", line 835, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'apps/frappe-list-unassign-from'
INFO: A newer version of bench is available: 5.16.2 → 5.16.4
```

**Comment by kid1194** [comment]
@crazy-explore-r I apologize for such problem..

This error is happening because the repo name doesn't match the plugin name and when bench installed the plugin it created the plugin folder using the repo name. The plugin name has underscores while the repo name has dashes..

I'm sorry, I don't know how to force bench to use the plugin name instead of repo..

Best regards..

**Comment by crazy-explore-r** [comment]
Noted @kid1194, Thanks
